name: 'Run package tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: 'Running tests'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
